services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car_school_automatization_backend
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/car_school_automatization_bd
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:17-alpine
    container_name: car_school_automatization_bd
    restart: unless-stopped
    environment:
      - POSTGRES_DB=car_school_automatization_bd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432" # 5432 - может быть занят
    volumes:
      - postgres_data_car_school_automatization:/var/lib/postgresql/data



volumes:
  postgres_data_car_school_automatization:



