spring:
  application:
    name: car_school_automatization
  
  datasource:
    url: jdbc:postgresql://localhost:5432/car_school_automatization_bd
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: eW91ci12ZXJ5LXNlY3JldC1rZXktdGhhdC1zaG91bGQtYmUtYXQtbGVhc3QtMjU2LWJpdHMtbG9uZy1mb3ItaHMyNTYtYWxnb3JpdGhtCg==
  expiration: 86400000